// GENERATED by scripts/gen-types.sh from `GET /api/v1/openapi.json` (§21).
// Do not edit by hand. PPF/Panel consume this file as the HTTP Source of Truth
// (snake_case, §20). CI regenerates it on changes and commits the result.
